language: node_js
node_js:
  - "lts/*"
branches:
  only:
  - master
cache:
  directories:
  - node_modules
  yarn: true
before_install:
- export TZ='Asia/Shanghai'
install:
- yarn
script:
- yarn docs:build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: dcdd5a9c33b55e947332c92aa79b0309c04cb347
  local-dir: ./sources/.vuepress/dist/
  target-branch: gh-pages
  verbose: true
  on:
    branch: master